In [1]:
import numpy as np
import pandas as pd

In [15]:
# Leitura do banco PAGE_HEI
page_hei = pd.read_csv('data/PAG_HEI.csv')

# renomeando as colunas
page_hei = page_hei.rename(columns={'SEQN': 'ID', 
                                    'PAG_MINW':'tempo_total_semanal_atividade', 
                                    'ADHERENCE':'aderencia',
                                    'HEI2015C1_TOTALVEG': 'total_vegetais',
                                    'HEI2015C2_GREEN_AND_BEAN':'verdura_verde_leguminosa',
                                    'HEI2015C3_TOTALFRUIT':'frutas_totais',
                                    'HEI2015C4_WHOLEFRUIT':'frutas_natura',
                                    'HEI2015C5_WHOLEGRAIN':'graos_integrais',
                                    'HEI2015C6_TOTALDAIRY':'laticinios',
                                    'HEI2015C7_TOTPROT':'proteinas',
                                    'HEI2015C8_SEAPLANT_PROT':'plantas_marinhas',
                                    'HEI2015C9_FATTYACID':'acido_graxo',
                                    'HEI2015C10_SODIUM':'sodio',
                                    'HEI2015C11_REFINEDGRAIN':'graos_refinados',
                                    'HEI2015C12_SFAT':'gordura_saturada',
                                    'HEI2015C13_ADDSUG':'acucares_adicionados',
                                    'HEI2015_TOTAL_SCORE':'score_total'})
page_hei

,ID,tempo_total_semanal_atividade,aderencia,total_vegetais,verdura_verde_leguminosa,frutas_totais,frutas_natura,graos_integrais,laticinios,proteinas,plantas_marinhas,acido_graxo,sodio,graos_refinados,gordura_saturada,acucares_adicionados,score_total
0,31128,NaN,NaN,3.083350,0.000000,3.927008,5.000000,0.000000,5.000000,4.251329,0.000000,2.487572,6.911882,10.000000,0.818029,6.408092,47.887262
1,31129,285.450346,2.0,1.697761,0.000000,3.731602,4.929186,0.527631,3.887809,4.693141,0.928562,3.740758,6.146441,7.274979,8.006457,0.000000,45.564326
2,31130,0.000000,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,31131,264.711316,2.0,3.115103,0.000000,5.000000,1.320674,0.000000,3.141062,4.071959,2.052399,0.684985,2.297100,9.512964,0.438428,3.919226,35.553899
4,31132,1353.348730,3.0,3.509081,0.000000,5.000000,5.000000,5.000000,4.448512,5.000000,0.000000,2.050769,7.369489,8.887880,8.186877,9.099088,63.551696
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9419,41469,184.711316,2.0,2.555935,0.000000,2.613733,0.000000,0.000000,2.151846,5.000000,0.000000,9.344947,3.535211,4.326307,5.269780,8.195564,42.993323
9420,41471,951.478060,3.0,2.674192,3.769401,2.198817,0.517369,0.463168,4.662005,5.000000,1.191796,6.145146,3.189620,3.766149,3.974279,7.758940,45.310883
9421,41472,27.713626,1.0,2.457422,2.930799,2.311917,0.000000,0.933303,5.000000,5.000000,5.000000,2.090534,8.409844,8.936854,3.063795,0.000000,46.134467
9422,41473,685.912240,3.0,3.907340,5.000000,0.000000,0.000000,0.000000,5.000000,5.000000,5.000000,0.000000,7.458058,10.000000,1.676912,2.751168,45.793478
9423,41474,0.000000,1.0,1.238646,4.610515,0.688137,0.240848,5.000000,5.000000,4.304982,5.000000,2.162293,7.018993,10.000000,7.541082,0.000000,52.805494

In [18]:
# Leitura do banco DEMO_PHQ
demo_phq = pd.read_csv('data/DEMO_PHQ.csv')

# Quantidade de nulos
demo_phq = demo_phq.rename(columns={'SEQN':'id',
                                    'DPQ010':'interesse_prazer_coisas',
                                    'DPQ020':'sentiu_pra_baixo',
                                    'DPQ030':'dificuldade_dormir',
                                    'DPQ040':'cansado_pouca_energia',
                                    'DPQ050':'falta_apetite',                                  
                                    'DPQ060':'sentiu_mal_consigo_mesmo',
                                    'DPQ070':'dificuldade_concentracao',
                                    'DPQ080':'lentidao_movimentacao',
                                    'DPQ090':'pensou_em_se_ferir',
                                    'RIAGENDR':'genero',
                                    'RIDAGEYR':'idade',
                                    'RIDRETH1':'raca_etnia',
                                    'DMDEDUC':'escolaridade',
                                    'INDFMINC':'renda_anual_familiar'})

demo_phq

,id,interesse_prazer_coisas,sentiu_pra_baixo,dificuldade_dormir,cansado_pouca_energia,falta_apetite,sentiu_mal_consigo_mesmo,dificuldade_concentracao,lentidao_movimentacao,pensou_em_se_ferir,genero,idade,raca_etnia,escolaridade,renda_anual_familiar
0,31130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,85,3,4,4.0
1,31131,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,44,4,4,11.0
2,31132,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,70,3,5,11.0
3,31134,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,73,3,3,12.0
4,31139,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,2,18,2,3,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5329,41466,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2,58,5,2,3.0
5330,41468,0.0,2.0,0.0,1.0,1.0,2.0,1.0,3.0,0.0,2,66,1,1,8.0
5331,41469,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1,19,4,4,2.0
5332,41472,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,34,3,4,7.0
5333,41473,0.0,0.0,2.0,1.0,0.0,1.0,0.0,0.0,0.0,1,21,1,2,6.0

In [26]:
# Combinando as duas tabelas
final_table = demo_phq.merge(right = page_hei, how='inner', left_index=True, right_index=True)
final_table

,id,interesse_prazer_coisas,sentiu_pra_baixo,dificuldade_dormir,cansado_pouca_energia,falta_apetite,sentiu_mal_consigo_mesmo,dificuldade_concentracao,lentidao_movimentacao,pensou_em_se_ferir,...,graos_integrais,laticinios,proteinas,plantas_marinhas,acido_graxo,sodio,graos_refinados,gordura_saturada,acucares_adicionados,score_total
0,31130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,5.000000,4.251329,0.000000,2.487572,6.911882,10.000000,0.818029,6.408092,47.887262
1,31131,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.527631,3.887809,4.693141,0.928562,3.740758,6.146441,7.274979,8.006457,0.000000,45.564326
2,31132,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,31134,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,3.141062,4.071959,2.052399,0.684985,2.297100,9.512964,0.438428,3.919226,35.553899
4,31139,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,...,5.000000,4.448512,5.000000,0.000000,2.050769,7.369489,8.887880,8.186877,9.099088,63.551696
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5329,41466,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,3.146111,2.472050,3.659525,5.000000,5.604361,7.170430,3.291488,4.634011,3.187386,41.784355
5330,41468,0.0,2.0,0.0,1.0,1.0,2.0,1.0,3.0,0.0,...,1.346121,5.000000,5.000000,2.523978,2.076821,6.910090,10.000000,5.449394,9.261834,64.635376
5331,41469,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,5.000000,4.037803,5.000000,5.000000,7.745917,0.000000,10.000000,10.000000,10.000000,74.065957
5332,41472,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,1.691079,4.766488,3.356393,4.533039,3.751504,8.682008,10.000000,0.000000,44.179366
5333,41473,0.0,0.0,2.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.332171,4.982561,5.000000,5.000000,9.819359,4.697448,8.739611,5.391816,6.105298,62.557223